version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: bim
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  controls:
    build:
      context: controls
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bim
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    depends_on:
      - db
  pricing:
    build:
      context: pricing
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/bim
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user
    depends_on:
      - db

volumes:
  postgres-data:
